### PR TITLE
Plugin links Addon Teaser

### PR DESCRIPTION
**Pull request by AlexGStapleton**

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. The link would need to be:

`https://siteorigin.com/downloads/premium/?featured_addon=plugin/web-font-selector`

**Review by Misplon — CHANGES_REQUESTED** [review]
Update URL.

**Comment by Misplon** [comment]
Mmm ok so is the purpose of the WB and PB link queries just for tracking?

**Comment by AlexGStapleton** [comment]
Honestly, I'm not sure. I just followed the link structure of the Page Builder link. Having it separate (rather than for a specific addon) would make it very obvious where the user clicked through from as I know there are links to the Web Font Selector addon page.

**Review by Misplon — APPROVED** [review]

**Pull request merged**
