### PR TITLE
Updated CodeMirror

### LINKED ISSUE #35: IE 11: Copy and Paste no Longer works (and other issues)
The copy and paste fix (context menu) ironically broke copy and paste in IE 11 in certain situations (making it either super complicated or impossible) and it also caused certain usability issues (like selecting text is a massive pain). 

Right click copy and paste doesn't work either - Paste is only visible when something is selected.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Was version 5.10, now 5.23.0 ([version history](http://codemirror.net/doc/releases.html)). I ran a number of tests and didn't come up with any issues.

This resolves #35, #55. Could resolve a few others too.

I applied the changes made in this commit also. 47e7850

### CODE REVIEW

**Comment by braamgenis** [comment]
@gregpriday I think we should see if we can make these changes ( https://github.com/siteorigin/so-css/commit/47e7850a0985f009b6c504c36920b66f3cece7cc ) somewhere in our own source, even if we have to duplicate that code. If it was me updating CodeMirror, I wouldn't have known to re-include those changes. I'll create an issue.

**Comment by gregpriday** [comment]
I actually forgot to check that. @AlexGStapleton - did you incorporate those changes?

**Comment by AlexGStapleton** [comment]
Uh, yeah... it says it in the PR which is why @braamgenis knew about it. :S

**Comment by gregpriday** [comment]
Awesome, nice work. I should really read PR messages ;)

**Comment by braamgenis** [comment]
:joy:

**Pull request merged**
