### PR TITLE
Resolve WC Tabs display issue

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/so-css/issues/90

### CODE REVIEW

**Comment by Misplon** [comment]
I'm getting the following:

Custom_CSS_‹_SiteOrigin_—_WordPress

This was after I tried pulling the wp.3.6-jquery-changes branch into this branch.

**Comment by AlexGStapleton** [comment]
> This was after I tried pulling the wp.3.6-jquery-changes branch into this branch.

So it worked prior to that? There's nothing that should really cause any issues as a result of the merge of the other PR but it's possible something went wrong during the branch merge.

**Comment by Misplon** [comment]
I couldn't get it to work before or after the merge.

**Comment by Misplon** [comment]
Here is what I'm seeing. I have SiteOrigin Premium deactivated.

[tabs-issue.mov.zip](https://github.com/siteorigin/so-css/files/5647033/tabs-issue.mov.zip)

**Comment by AlexGStapleton** [comment]
Thank you for the video. The last commit should resolve this.

**Review by Misplon — APPROVED** [review]

**Comment by Misplon** [comment]
@AlexGStapleton Looking great! A quick conflict above, then we should be good to go.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
